#!/bin/sh
while read file
do
  FILE_FULL_PATH=$(readlink -f "$file")
  case $1 in
    "D")
      rm "$FILE_FULL_PATH"
      ;;
    "w")
      echo "Setting wallpaper:" "$FILE_FULL_PATH"
      feh --bg-center "$FILE_FULL_PATH"
      notify-send -i "$FILE_FULL_PATH" "Wallpaper changed"
      ;;
  esac
done
