#!/bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom --experimental-backends &
feh --bg-fill ~/.config/wallpapers/wallpaper_001.jpg &
dunst -conf ~/.config/dunst/dunstrc &
~/.config/polybar/launch.sh &

# monitors
# ~/.local/share/scripts/set_bspwm_monitors.sh
# bspc monitor eDP -d V VI VII VIII
# bspc monitor HDMI-A-1 -d I II III IV

bspc monitor HDMI-A-0 -d 1 2 3 4
bspc monitor eDP -d 5 6 7 8

# window information
bspc config border_width 0
bspc config window_gap 6

# bspc config focused_border_color "#5E81AC"
# bspc config normal_border_color "#4c566a"
bspc config ignore_ewmh_struts

bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config focus_follows_pointer      true
# bspc config pointer_follows_monitor    true
bspc config pointer_modifier           mod4
# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

# rules
# bspc rule -a mumble state=floating follow=on focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
